### ISSUE TITLE
タイムラインのカラムにてツイートを表示するとカラムが真っ白になる問題

### ISSUE THREAD

**Issue by liseviero** [kawa-nobu/Open-Deck#1]
タイムラインのつぶやきクリックしたら詳細表示されずカラムが真っ白になります。
他のカラムは正常です。
修正お願いします。

**Comment by kawa-nobu** [comment]
各カラムのトップ非表示で真っ白になっているのでしょうか?
上記バグの場合、既知の問題で把握しております。
回避法として、画像のように「Top」にチェックを行い再度チェックを外すと正常に表示されるかと思います。
<img alt="image" src="https://github.com/kawa-nobu/Open-Deck/assets/44832116/ff27c240-931a-442d-a3fd-1dbc64fb7c67">
もう少し違うバグであれば、
背景情報(お使いの環境、設定の項目、バグが発生した手順、発生頻度)を頂ければ詳細なデバッグが可能なのでご協力願います。
また、気軽にバグ報告などするときはDiscordもおすすめです。
専用のコミュニティを開設しておりますので、併せてご活用ください。
https://discord.com/invite/s7hUjKSE3K
よろしくお願いいたします。

**Comment by liseviero** [comment]
問題解決しました！ありがとうございます。
コミュニティも入らせて頂きました。
今後の更新楽しみです。

**Comment by kawa-nobu** [comment]
試作版Ver.1.0.7で修正しました
