### ISSUE TITLE
プロファイルの有無がぱっと見でわからない

### ISSUE THREAD

**Issue by niwanowa** [kawa-nobu/Open-Deck#2]
動作環境
Google Chrome
バージョン: 122.0.6261.112（Official Build） （64 ビット）

Open-Deck
バージョン
1.0.1

以下の画像のようにマウスオーバーをすると保存されたプロファイルの有無が確認できるが、
保存されたプロファイルの全量を確認はできない
![image](https://github.com/kawa-nobu/Open-Deck/assets/40478818/20a9800e-83ef-41f1-91d7-cd7d31669b65)

不明点など、こちらでも反応します
https://twitter.com/niwa_nowa

**Comment by kawa-nobu** [comment]
ダークモード関連でバグが発生していますね
ダークモードは文字が白色になり背景が黒になるのですが、
スクリーンショットの方は文字が白色になり、背景が黒色になっていない様です。
私の方でも試しましたが、ダークモード時に背景を強制的に白色にすると同様の現象になりました。
<img width="165" alt="image" src="https://github.com/kawa-nobu/Open-Deck/assets/44832116/3b6f7338-dbd0-413d-98a0-bc61cd61bd28"> <img width="199" alt="image" src="https://github.com/kawa-nobu/Open-Deck/assets/44832116/99737498-a425-45c9-a578-286326d10888">

ダークモードの動作はブラウザ側のCSS制御に任せているので、ダークモード関連の拡張機能が動作を邪魔している可能性があります。ご確認のほどよろしくお願いいたします

**Comment by niwanowa** [comment]
![image](https://github.com/kawa-nobu/Open-Deck/assets/40478818/7772a6c8-13bc-4925-91dc-23f44d7cb5d3)
確かにシークレットモードで実行すると各文字がきちんと表示されていました。

追加で色々設定変更して確認してみて解決しましたので知見を共有いたします。

解決した設定変更
・OSのモードをダークに変更する
![image](https://github.com/kawa-nobu/Open-Deck/assets/40478818/cb1e4cb9-3682-4541-a04d-e09ffaab7587)

解決しなかった設定変更
・Chromeのテーマをデフォルトに変更する
・Chromeの拡張機能をOpen-Deck以外無効にする
・Chromeのモードを明/暗/デバイスに切り替える
![image](https://github.com/kawa-nobu/Open-Deck/assets/40478818/0225b38e-f073-4ae0-bd13-0720fab55859)


開発者モードでCSSを確認してみると
以下を有効無効切り替えると文字が見えるようになりました。
color-scheme: dark;

**Comment by kawa-nobu** [comment]
調査・検証ありがとうございます
ダークモードの切り替えはOSとブラウザ・テーマによる相性もある為、今回は現状のままにしておきますね。
また問題が発生したらご連絡ください！
